### ISSUE TITLE
Add build configuration

### ISSUE THREAD

**Issue by wikier** [tteguayco/JITRAX#2]

**Comment by tteguayco** [comment]
Hi, wikier! Thanks for opening this issue. Could you provide a more detailed description?

**Comment by wikier** [comment]
Well, basically the install instructions point to execute a binary available in the source repository. Actually it should provide a way to build the binary from the source, ant that `.jar` should be removed from here.

**Comment by tteguayco** [comment]
I will add build configurations, thanks!

**Comment by tteguayco** [comment]
Added build configurations. I close this issue.
